### PR TITLE
Added vertical slider

### PR DESCRIPTION
**Pull request by Buzut**
As I had suggested in issue [#16](https://github.com/tyleryasaka/semantic-ui-range/issues/16), I've added a vertical mode.

### CODE REVIEW

**Comment by Buzut** [comment]
Yet, I have no problem with it. Here's a [working fiddle ](http://codepen.io/anon/pen/VPRrOx)

**Comment by tyleryasaka** [comment]
@Buzut Thanks for posting the fiddle. I see the problem now. You're using jQuery 3.x, but I was using 2.1.4.

**Comment by tyleryasaka** [comment]
@Buzut Looking into the issue some more, here's what I found:

In jQuery 2.x, the `width()` and `height()` methods return the same values, *even after an element has been rotated with css*. In jQuery 3.x, the `width()` and `height()` take the rotation into account.

Since jQuery 3 is still relatively new, I think this should remain 2.x compatible if possible. I think the best solution is going to involve updating the stylesheets to assign the correct width and height to vertical sliders without a css transform.

**Comment by Buzut** [comment]
@tyleryasaka I'm not sure I'm getting it. What do you mean by updating the stylesheet? Pragrammatically set the new width and height with `css` method so that jQuery returns the right values?

Also, we could simply swap width and height to get the right values when jQuery 2.x is used (using `$.fn.jquery` to get jQuery's version).

**Comment by tyleryasaka** [comment]
@Buzut I mean using the `range.css` stylesheet to apply different width/height values to sliders with class `vertical` - if that makes sense.

Yeah you could swap the width and height for jQuery 2. I'd prefer not to do it that way though; seems like a hack.

**Comment by Buzut** [comment]
Updated and now works with jQuery < 3.x. I tested with 2.2.4, see on [codepen](http://codepen.io/anon/pen/VPRrOx).

**Comment by tyleryasaka** [comment]
@Buzut Nice work - it does function - but this still isn't the approach that I prefer. Aside from feeling a bit hacky to me, the behavior is a bit odd; in the codepen you linked, I can click far to the left or right of the slider and still move the thumb. And if I mess with the container width at all, things break down pretty quickly.

I hope this isn't taken the wrong way as you have done good work on this. I'm just very particular about the code that I host on my own page. I'd implement this myself, but I have a lot of higher priority things so I'm not sure when I will get around to it.

If you'd rather not worry about getting anything merged into this repo, I can link to your fork from my readme so that other people that are looking for vertical sliders can use your code if they like.

**Comment by Buzut** [comment]
@tyleryasaka You're right, because of the modified height, you can click far on the side and it still stiggers the slider. Definitely better used with jQuery 3.x. Actually, to circumvent that, I might add a jQuery version detection and not change the height if version 3 is used.

Nevertheless, I can't figure out how you'd like to use a width in the stylesheet as it's not fixed. It depends on the container so you have to set it dynamically.

Anyhow, I don't have much time to digg deeper into this. I'd be glad if you link my fork from your readme. Moreover, please ping me when you have found an elegant solution to this.

**Comment by tyleryasaka** [comment]
@Buzut I linked to your fork in the readme.

**Comment by Buzut** [comment]
@tyleryasaka Thanks! I shall close the PR then.

**Pull request closed without merging**
